### PR TITLE
Implemented resource management for user

### PR DESCRIPTION
**Pull request by rusiruavb**
- Add user resource information to react bootstrap table
- Change create resource component to modal
- Modify the resource actions and reducer functions

### CODE REVIEW

**Review by RaveenaWickramasinghe — DISMISSED** [review]
LGTM

**Review by rusiruavb — COMMENTED** [review]
LGTM guys

**Review by Parathantl — DISMISSED** [review]

**Review by rusiruavb — COMMENTED** [review]
LGTM again

**Review by RaveenaWickramasinghe — APPROVED** [review]
LGTM

**Pull request merged**
